In [14]:
import numpy as np

a = np.zeros((8,8))
a[1::2, 0::2] = 1 # нечет i, чет j | начинает с [1] до конца с шагом 2 / начинает с [0] до конца с шагом 2
a[0::2, 1::2] = 1 # чет i, нечет j

print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]

In [15]:
m = np.arange(0, 5) + np.zeros((5,1))
print(m)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

In [16]:
m = np.random.random((3,3,3))
print(m)

[[[0.28536402 0.65613366 0.75112811]
  [0.22464357 0.42110066 0.35131972]
  [0.03421902 0.97549774 0.60581434]]

 [[0.13063092 0.6734627  0.04961944]
  [0.61056673 0.38236883 0.89180811]
  [0.9034797  0.72265573 0.21768773]]

 [[0.69529972 0.59947834 0.58374303]
  [0.81155182 0.18959059 0.58398909]
  [0.27683967 0.10247607 0.41836462]]]

In [17]:
u = np.ones((1,3))
m = np.zeros((3,3))
res = np.concatenate((u,m),axis=0)
res = np.concatenate((res,u),axis=0)
l = np.ones((5,1))
res = np.concatenate((l, res), axis=1)
res = np.concatenate((res,l), axis=1)
print(res)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

In [18]:
m = np.random.random((10))
print(np.sort(m)[::-1])

[0.86740666 0.85997573 0.82862826 0.78881292 0.50587167 0.45668042
 0.337837   0.28247997 0.21575726 0.01170607]

In [19]:
m = np.arange(0, 5) + np.zeros((5,1))
print(m)
print(m.shape, m.size, m.ndim)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
(5, 5) 25 2

In [20]:
import pandas as pd
import numpy as np

s1 = pd.Series([1, 2])
s2 = pd.Series([4, 5])
res1 = np.linalg.norm(s1 - s2)
res2 = np.sqrt((s2[1] - s1[1])**2 + (s2[0] - s1[0])**2)


print(f"Евклид по функции: {res1}")
print(f"Евклид по рассчету: {res2}")

Евклид по функции: 4.242640687119285
Евклид по рассчету: 4.242640687119285

In [21]:
url = "https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/diabetes.csv"
df = pd.read_csv(url)

In [22]:
df.head(2)
df.tail(3)
df.shape
df.describe

<bound method NDFrame.describe of      Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No
1     58    Male       No         No                 No      Yes         No
2     41    Male      Yes         No                 No      Yes        Yes
3     45    Male       No         No                Yes      Yes        Yes
4     60    Male      Yes        Yes                Yes      Yes        Yes
..   ...     ...      ...        ...                ...      ...        ...
515   39  Female      Yes        Yes                Yes       No        Yes
516   48  Female      Yes        Yes                Yes      Yes        Yes
517   58  Female      Yes        Yes                Yes      Yes        Yes
518   32  Female       No         No                 No      Yes         No
519   42    Male       No         No                 No       No         No

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes
1               No             Yes      No           No              No
2               No              No     Yes           No             Yes
3              Yes              No     Yes           No             Yes
4               No             Yes     Yes          Yes             Yes
..             ...             ...     ...          ...             ...
515             No              No     Yes           No             Yes
516             No              No     Yes          Yes             Yes
517             No             Yes      No           No              No
518             No             Yes     Yes           No             Yes
519             No              No      No           No              No

    partial paresis muscle stiffness Alopecia Obesity     class
0                No              Yes      Yes     Yes  Positive
1               Yes               No      Yes      No  Positive
2                No              Yes      Yes      No  Positive
3                No               No       No      No  Positive
4               Yes              Yes      Yes     Yes  Positive
..              ...              ...      ...     ...       ...
515             Yes               No       No      No  Positive
516             Yes               No       No      No  Positive
517             Yes              Yes       No     Yes  Positive
518              No               No      Yes      No  Negative
519              No               No       No      No  Negative

[520 rows x 17 columns]>

In [23]:
df.iloc[:6]

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
5,55,Male,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Positive

In [24]:
df[df['Age'] > 50].head(3)

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
5,55,Male,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Positive

In [25]:
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [27]:
from sklearn import preprocessing

minmax_scaler = preprocessing.MinMaxScaler()
standart_scaler = preprocessing.StandardScaler()
dfTest = dataframe.copy()

dfTest.columns

dfTest['sepal_length_cm'] = minmax_scaler.fit_transform(dfTest[['sepal_length_cm']])
dfTest['sepal_width_cm'] =standart_scaler.fit_transform(dfTest[['sepal_width_cm']])
dfTest

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,0.222222,1.032057,1.4,0.2,setosa
1,0.166667,-0.124958,1.4,0.2,setosa
2,0.111111,0.337848,1.3,0.2,setosa
3,0.083333,0.106445,1.5,0.2,setosa
4,0.194444,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,0.666667,-0.124958,5.2,2.3,virginica
146,0.555556,-1.281972,5.0,1.9,virginica
147,0.611111,-0.124958,5.2,2.0,virginica
148,0.527778,0.800654,5.4,2.3,virginica
149,0.444444,-0.124958,5.1,1.8,virginica